### ISSUE TITLE
Theme loads with errors

### ISSUE THREAD

**Issue by peteyy** [rakr/vim-two-firewatch#1]
https://dl.dropboxusercontent.com/1/view/5eeo8ycydhe1n6c/Apps/Shutter/Selection_005.png

By default it does not load the theme when I try to load twofirewatch theme. 
When I source my vimrc it gives me errors and hangs the terminal for a while but the colors get fixed.

My vimrc looks like the following:
https://github.com/peteyy/dotfiles/blob/master/config/nvim/init.vim#L346

**Comment by rakr** [comment]
Hi @peteyy you seem to run an older version that had the bug. Your `init.vim` seems to be correct.
Seeing that you are also using **Plug**, do you mind running the command `PlugUpdate` to get the last version?

Make sure you exit and reload Neovim.

**Comment by peteyy** [comment]
I updated the plugins but according to the changelog I was running the latest two-firewatch. Could this be linux related?

**Comment by rakr** [comment]
Don't think so, I had the same problem when I added this airline theme on a Mac. To start on a clean slate, I suggest you remove the colorscheme folder from your `Plugged` folder and try to reinstall it again.

The colorscheme is working properly, the problem seem to be with the airline theme.

**Comment by peteyy** [comment]
I tried to remove all the plugins from my bundle folder. 
It still makes no change in the airline theme by default, but after first sourcing it looks like this. 
https://dl.dropboxusercontent.com/1/view/m2zx5l7e8gokb2t/Apps/Shutter/Selection_006.png

After sourcing the second time it gives me the errors and then it works properly.

**Comment by rakr** [comment]
Weird, can you please check the content of the following file:
`bundle/vin-twofirewatch/autoload/airline/themes/twofirewatch`, it should not contain any reference to `g:airline#themes#one` but instead `g:airline#themes#twofirewatch`.

**Comment by peteyy** [comment]
It has no reference to `g:airline#themes#one` all of them are `twofirewatch`

**Comment by rakr** [comment]
Got it, it's actually a bug, will be posting an update very soon.

**Comment by rakr** [comment]
Just pushed an update, run `PlugUpdate and let me know

**Comment by peteyy** [comment]
Airline works great now. Thanks for the fast response and fix, you're awesome!

I also noticed this issue:
https://dl.dropboxusercontent.com/1/view/xbws1iq96xg1dts/Apps/Shutter/Selection_007.png

If I open up a file in TMUX the background of some text (comments mostly) change and make it harder to read. Should I file another issue with this?

**Comment by rakr** [comment]
No worries, thanks for documenting the issue.
I've also noticed a change with tmux, can you please open a new issue and attach your screenshot directly yo it (instead of linking to a dropbox file :D )
