### ISSUE TITLE
Operator group is not highlighted

### ISSUE THREAD

**Issue by mkalinski** [rakr/vim-two-firewatch#2]
As seen in the attached screenshot. Operator group has the same color as base text. This is a problem for languages which have operators which are text keywords (ex. "sizeof")

![tf-oper](https://cloud.githubusercontent.com/assets/959502/17480275/5e8373b6-5d77-11e6-8bbe-02d5b4ebd2cd.png)

I'm using Neovim 0.1.5-dev on Ubuntu 16.

**Comment by rakr** [comment]
Thanks for your feedback and also opening the issue. I have changed the `Operator` highlighting in order to use of accent color.
Enjoy
